### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by eislasq** [playmusicdecrypter/playmusicdecrypter#10]
Hello I tried to decrypt files previously pulled from my device with the following command.

``` shell
./playmusicdecrypter -d ~/Música/databases/music.db -l ~/Música/files/music ~/Música/files/decriptedMusic/
```

but i got the following output

``` shell
Decrypting MP3 files...
Traceback (most recent call last):
  File "./playmusicdecrypter", line 4, in <module>
    playmusicdecrypter.main()
  File "/home/eislas/bin/playmusicdecrypter/playmusicdecrypter.py", line 226, in main
    decrypt_files(options.library, destination_dir, options.database)
  File "/home/eislas/bin/playmusicdecrypter/playmusicdecrypter.py", line 179, in decrypt_files
    print(u"  Skipping file {} ({})".format(f, e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
```

Could some one help me to know how to resolve this problem please.

**Comment by nopnop9090** [comment]
put the files in a directory like Music - you are having non-ascii characters in your path (ú) that makes the script choke
