### ISSUE TITLE
Cannot Find the File Specified

### ISSUE THREAD

**Issue by Sokmeng007** [playmusicdecrypter/playmusicdecrypter#15]
I have everything installed.
Then I ran `playmusicdecrypter.py`...It showed `cannot find the file specfied`.
Then I tried `playmusicdecrypter E:\` Still face the same problem.

Maybe I don't how to run. 
Please help.

**Comment by chriscz** [comment]
Please post a tracback of the error (what you saw in the terminal / command prompt).

**Comment by Sokmeng007** [comment]
Thanks for your reply. It looks like this:

E:\playmusicdecrypter-master>playmusicdecrypter.py E:\
Downloading Google Play Music database from device...
Traceback (most recent call last):
  File "E:\playmusicdecrypter-master\playmusicdecrypter.py", line 229, in <modul
e>
    main()
  File "E:\playmusicdecrypter-master\playmusicdecrypter.py", line 217, in main
    pull_database(destination_dir, adb=options.adb)
  File "E:\playmusicdecrypter-master\playmusicdecrypter.py", line 123, in pull_d
atabase
    adb = superadb.SuperAdb(executable=adb)
  File "E:\playmusicdecrypter-master\superadb.py", line 107, in **init**
    self.start_server()
  File "E:\playmusicdecrypter-master\superadb.py", line 120, in start_server
    return self.adb("start-server")
  File "E:\playmusicdecrypter-master\superadb.py", line 116, in adb
    return subprocess.call([self.executable] + list(cmd))
  File "C:\Python27\lib\subprocess.py", line 523, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 711, in **init**
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by chriscz** [comment]
Looks like you don't have `adb` available on your path. Consider using the `-a` flag of the script to specify the path to `adb`. There's more details in the help section of the [README](https://github.com/playmusicdecrypter/playmusicdecrypter).

**Comment by Sokmeng007** [comment]
Sorry to bother you again.
I figured out how to add adb to the path. But still fail:

E:\playmusicdecrypter-master>playmusicdecrypter.py C:\

## Downloading Google Play Music database from device...

Exception happened during processing of request from ('127.0.0.1', 25454)
Traceback (most recent call last):
  File "C:\Python27\lib\SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\lib\SocketServer.py", line 652, in __init__
    self.handle()
  File "E:\playmusicdecrypter-master\superadb.py", line 34, in handle
    self.handle_pull()
  File "E:\playmusicdecrypter-master\superadb.py", line 40, in handle_pu
ll
    with open(self.server.local_file, "wb") as f:

## IOError: [Errno 13] Permission denied: 'C:\music.db'

nc: short write
  Download failed! Exiting...

**Comment by chriscz** [comment]
Are you sure you enabled development mode on your phone?
Alternatively, pick a location on your Desktop, not the `C:/` drive
Could you try placing it somewhere else? like on your desktop or even `E:/`?

Also, place your exception traces between three backticks (&grave;&grave;&grave;):

&grave;&grave;&grave;
**\* exception dump here ***
&grave;&grave;&grave;

**Comment by Sokmeng007** [comment]
I take a step further. I run the cmd as administrator and I got this:
(USB debugging is connected). 

C:\Users\HSokmeng\Desktop\playmusicdecrypter-master>playmusicdecrypter.py E:/
Downloading Google Play Music database from device...
Downloading encrypted MP3 files from device...
  Downloading file 1/9...sh: can't open /data/data/com.google.android.music/file
s/music2_632.mp3: No such file or directory
  Downloading file 2/9...sh: can't open /data/data/com.google.android.music/file
s/music305.mp3: No such file or directory
  Downloading file 3/9...sh: can't open /data/data/com.google.android.music/file
s/music521.mp3: No such file or directory
  Downloading file 4/9...sh: can't open /data/data/com.google.android.music/file
s/music533.mp3: No such file or directory
  Downloading file 5/9...sh: can't open /data/data/com.google.android.music/file
s/music534.mp3: No such file or directory
  Downloading file 6/9...sh: can't open /data/data/com.google.android.music/file
s/music556.mp3: No such file or directory
  Downloading file 7/9...sh: can't open /data/data/com.google.android.music/file
s/music568.mp3: No such file or directory
  Downloading file 8/9...sh: can't open /data/data/com.google.android.music/file
s/music608.mp3: No such file or directory
  Downloading file 9/9...sh: can't open /data/data/com.google.android.music/file
s/music619.mp3: No such file or directory

  All downloads finished (4.5s)!
Decrypting MP3 files...
  No files found! Exiting...

**Comment by chriscz** [comment]
Awesome, what android version do you have?

**Comment by Sokmeng007** [comment]
Android 6.0.

**Comment by chriscz** [comment]
You can look at http://android.stackexchange.com/questions/122547/cannot-find-where-google-play-music-stores-downloaded-files-different-from-simi maybe the location of the files have changed in the more recent android versions. 

You can run `adb shell` to open a shell to your phone.

Then you can use `cd` to enter a directory and `ls` to list/show the files in the current directory.

**Comment by chriscz** [comment]
Apparently it should be under `/data/data/com.google.android.music/files/music`

**Comment by Sokmeng007** [comment]
I use file explorer on my phone and see the mp3 file are in two directories: 
1. data/user/0/com.google.android.music
2. data/data/com.google.android.music.

**Comment by Sokmeng007** [comment]
I even copy those mp3 files to other place and change the source_dir in the Phyton code. Still Fail. Maybe because of my phone.

**Comment by chriscz** [comment]
Well, then I don't really know what to do. 
I've never used the script so that was going to be my suggestion.

Please post here if you figure it out!

**Comment by Sokmeng007** [comment]
Yeah thanks so much for spending your time helping me. Good luck..

**Comment by chriscz** [comment]
It's a pleasure. Last thing I can think of is copying the files to your
computer manually and changing a bit of the source to decrypt them. It
should be straightforward.

**Comment by zakisaad** [comment]
Yup, had the same issues as above. Modified the script to take local files as source worked well, thanks for your work!

**Comment by privatesam** [comment]
Hi @zakisaad do you mind sharing the modified script for local files please?
