### ISSUE TITLE
OsError: NoSuch file or directory

### ISSUE THREAD

**Issue by Myselfminer** [playmusicdecrypter/playmusicdecrypter#7]
python playmusicdecrypter.py /Music/
Downloading Google Play Music database from device...
Traceback (most recent call last):
  File "playmusicdecrypter.py", line 229, in <module>
    main()
  File "playmusicdecrypter.py", line 217, in main
    pull_database(destination_dir, adb=options.adb)
  File "playmusicdecrypter.py", line 123, in pull_database
    adb = superadb.SuperAdb(executable=adb)
  File "/home/david/playmusicdecrypter-master/superadb.py", line 107, in **init**
    self.start_server()
  File "/home/david/playmusicdecrypter-master/superadb.py", line 120, in start_server
    return self.adb("start-server")
  File "/home/david/playmusicdecrypter-master/superadb.py", line 116, in adb
    return subprocess.call([self.executable] + list(cmd))
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I am using a rooted Samsung SM-T230 with busybox installed

**Comment by chriscz** [comment]
Looks like it can't find your adb executable.
Does running adb actually work?

**Comment by Myselfminer** [comment]
Yes, and android studio uses it well

**Comment by Ph0t0nX** [comment]
I had the same issue, but then I added C:\sdk\platform-tools (the path to adb) to my Path environment variable, reopened my command prompt for the setting to take effect, and then it was able to get past that error. Now it says 

C:\Python27\pmd>playmusicdecrypter.py f:/out
Downloading Google Play Music database from device...
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
  Download failed! Exiting...

So I'm looking into that issue.
